apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chandra-admin
  namespace: postgres-ns
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chandra-admin-binding
  namespace: postgres-ns
subjects:
- kind: User
  name: chandra
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: chandra-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chandra-admin1
  namespace: wordpress-ns
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chandra-admin1-binding
  namespace: wordpress-ns
subjects:
- kind: User
  name: chandra
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: chandra-admin1
  apiGroup: rbac.authorization.k8s.io