apiVersion: v1
kind: Namespace
metadata:
  name: wordpress-ns
  labels:
    app: wordpress-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  namespace: wordpress-ns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wordpress-cont
        image: wordpress
        env:
        - name: WORDPRESS_DB_NAME
          value: postgresdb
        - name: WORDPRESS_DB_HOST
          value: "postgres-db:5432"
        - name: WORDPRESS_DB_USER
          value: chandra_test
        - name: WORDPRESS_DB_PASSWORD
          value: chandra_test
        ports:
        - containerPort: 8080
      nodeSelector:
        compute: Application

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: wordpress-ns
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: wordpress-app
  type: NodePort