apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-db
  namespace: postgres-ns
  labels:
    app: wordpress-db
spec:
  limits:
  - max:
      cpu: "900m"
      memory: 900Mi
    min:
      cpu: "200m"
      memory: 300Mi

    type: Pod

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: microk8s-hostpath
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: postgres-ns
  labels:
    app: wordpres-db
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: postgres-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: postgres-ns
  labels:
    app: wordpres-db
spec:
  serviceName: "postgres-svc"
  replicas: 1
  selector:
    matchLabels:
      app: wordpres-db
  template:
    metadata:
      labels:
        app: wordpres-db
    spec:
      containers:
      - name: postgres-cont
        image: postgres:12
        env:
        - name: POSTGRES_PASSWORD
          value: chandra_test
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "768Mi"
            cpu: "300m"
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: pv-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim
      nodeSelector:
        compute: DB

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: postgres-ns
  labels:
    app: wordpres-db
spec:
  ports:
  - port: 5432
  selector:
    app: wordpres-db
  type: ClusterIP